name: CI Test Pipeline

on:
  push:
    branches: [ "ci-cd-setup" ]
  pull_request:
    branches: [ "ci-cd-setup" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, bcmath, mysql, xdebug
        coverage: xdebug

 - name: Create storage directories
      run: |
        mkdir -p storage/framework/{cache,sessions,views}
        mkdir -p storage/logs

    - name: Copy .env
      run: cp .env.testing .env

    - name: Update .env database values
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=test_db" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env

    - name: Composer install
      run: composer install --no-interaction --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run PHPUnit tests with coverage
      run: php artisan test --coverage-clover coverage.xml

    - name: Upload PHP test results
      uses: actions/upload-artifact@v4
      with:
        name: phpunit-coverage
        path: coverage.xml

  cypress-tests:
    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Start Laravel server
      run: php artisan serve --port=8000 &

    - name: Wait for server
      run: npx wait-on http://127.0.0.1:8000

    - name: Run Cypress tests
      run: npx cypress run --config-file cypress/cypress.compress.config.js

    - name: Upload Cypress videos & screenshots
      uses: actions/upload-artifact@v4
      with:
        name: cypress-results
        path: cypress/videos
